language: python
virtualenv:
  system_site_packages: true
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
before_install:
  - "sudo apt-get install python-gi python3-gi"
install:
  - "pip install --use-mirrors setuptools twisted tornado"
  - "DEPS=`python bin/deps.py`"
  - "echo $TRAVIS_PYTHON_VERSION $DEPS"
script: python setup.py test
