language: python
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install python-gi python3-gi"
install:
  - "pip install tox"
script:
  - "tox"
  - "coverage combine"
  - "coverage report"
after_success:
  - "coveralls"

